### PR TITLE
add default ignoreMembers to suppress underscore-prefixed members

### PR DESCRIPTION
**Pull request by cmichaelgraham**
add default ignoreMembers to suppress underscore-prefixed members

(until meta passing mechanism can be fixed)

---

This change is [Reviewable](https://reviewable.io/reviews/yolodev/babel-dts-generator/47)

### CODE REVIEW

**Comment by Alxandr** [comment]
Is there already tests for class members starting with underscore? And interface members? If not, please add.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/47#-:-KKT-hbpyjT7tQaOGVS_:-258436220)_

**Comment by Alxandr** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/export/export-suppress-underscore.src.js, line 20 [r2]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/47#-KKUDHT7TLYxhk8CV4rW:-KKUDHT7TLYxhk8CV4rX:-1188891641) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/aac214a53a1efb49901363c7e038e2e8e5b4414b/spec/export/export-suppress-underscore.src.js#L20)):_

> ``` JavaScript
> interface _foofootwo {
> 
> }
> ```

You're missing a newline. Once this is fixed, just go ahead and merge and release :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/47)_

**Comment by cmichaelgraham** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/export/export-suppress-underscore.src.js, line 20 [r2]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/47#-KKUDHT7TLYxhk8CV4rW:-KKXlZIsW2BCy4_-aF1O:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/aac214a53a1efb49901363c7e038e2e8e5b4414b/spec/export/export-suppress-underscore.src.js#L20)):_
<details><summary>

<i>Previously, Alxandr (Alxandr) wrote…</i></summary>



> You're missing a newline. Once this is fixed, just go ahead and merge and release :)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/47)_

**Comment by Alxandr** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/47)_

**Pull request merged**
