### PR TITLE
Aurelia work

### PR DESCRIPTION
**Pull request by cmichaelgraham**
import working.

all tests passing.

need code review :+1:

[Review on Reviewable](https://reviewable.io/reviews/yolodev/babel-dts-generator/36)

### CODE REVIEW

**Comment by Alxandr** [comment]
I've added inline responses to a few points. Mostly small stuff. Some of them affect more places than the inline comments though.

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[spec/function/export-class-with-function-object-hybrid.expected.ts, line 7 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoITv-iI8Pc6Us4hnj:-KAoITv01q0l7qPKAtTH:1684066874) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/function/export-class-with-function-object-hybrid.expected.ts#L7)):_
Capital letter is probably better.

---

_[spec/function/export-class-with-function-object-hybrid.src.js, line 8 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoIZ9BJD9Xg3Qb1gXw:-KAoIZ9BJD9Xg3Qb1gXx:-1598828166) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/function/export-class-with-function-object-hybrid.src.js#L8)):_
Same here obviously, capital letter on class names.

---

_[spec/nullable/nullable-parameter.expected.ts, line 1 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoImhpidt_bOSuQYxi:-KAoImhpidt_bOSuQYxj:-1738582958) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/nullable/nullable-parameter.expected.ts#L1)):_
My browser is showing some weird symbols here. Lack of newline at the end?

---

_[spec/nullable/nullable-parameter.src.js, line 3 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoIs_5Lnviat1aEK6l:-KAoIs_5Lnviat1aEK6m:-2124468616) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/nullable/nullable-parameter.src.js#L3)):_
Same here with weird symbols at the end.

---

_[src/generators/ast.js, line 9 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJ1uyiFe2yD1rujNB:-KAoJ1uyiFe2yD1rujNC:-665869459) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L9)):_
Not all nodes can have decorators. This should be moved to somewhere for which nodes can have decorators IMHO. Maybe something like a `DecorableNode` which extends node and overrides the `fromSource` method. And have `ClassNode` and the others in question inherit from it.

Also, you don't test for the following pattern:

``` js
// this is comment 1
@deco
// this is comment 2
class Foo {}
```

I would expect both comments to survive I think. So the arrays should be merged (`use [].concat(node.leadingComments, decoLeadingComments)` or similar).

---

_[src/generators/ast.js, line 19 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJsJ6Cdptf2YdTfiT:-KAoJsJ6Cdptf2YdTfiU:2004789312) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L19)):_
Has it become optional to include code? Anyways, more importantly, spaces after `{` and before `}`, so `{ includeComment = true, includeCode = false }`. Isn't there a `.eslintrc` file includeded? I need to setup eslint to run as part of testing...

---

_[src/generators/ast.js, line 264 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoKyFNL0CoaBxvJxlA:-KAoKyFNL0CoaBxvJxlB:988369046) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L264)):_
I think maybe we ought to creates line-breaks between each specifier like such:

``` js
import {
  foo,
  bar as baz,
  foobar } from 'foo-bar';
```

Mainly cause of scalability.

In general, when auto-generating stuff like this I've found this to work better :).

The same goes for exports btw.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-:-KAoLqLPMzz-vyzwZdzC:151604164)_

**Comment by cmichaelgraham** [comment]
Review status: 15 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

_[spec/function/export-class-with-function-object-hybrid.expected.ts, line 7 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoITv-iI8Pc6Us4hnj:-KArL_8YA-lo9CwbdSeW:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/function/export-class-with-function-object-hybrid.expected.ts#L7)):_
Done.

---

_[spec/function/export-class-with-function-object-hybrid.src.js, line 8 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoIZ9BJD9Xg3Qb1gXw:-KArLt5XFdsmTOEVLSZI:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/function/export-class-with-function-object-hybrid.src.js#L8)):_
Done.

---

_[spec/nullable/nullable-parameter.expected.ts, line 1 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoImhpidt_bOSuQYxi:-KArMP-8iORbu-R9iHwz:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/nullable/nullable-parameter.expected.ts#L1)):_
Done.

---

_[spec/nullable/nullable-parameter.src.js, line 3 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoIs_5Lnviat1aEK6l:-KArMWLLbSZVVzyfX6Om:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/spec/nullable/nullable-parameter.src.js#L3)):_
Done.

---

_[src/generators/ast.js, line 9 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJ1uyiFe2yD1rujNB:-KArSFJTNbQk29WLbvem:254114631) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L9)):_
i'll follow the suggestion.  initially, i will have the ClassDeclaration and ClassMethod derive from the new derived class

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36)_

**Comment by cmichaelgraham** [comment]
Review status: 13 of 24 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[src/generators/ast.js, line 9 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJ1uyiFe2yD1rujNB:-KAyXmj2402u26nGeHXv:1907479860) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L9)):_
ClassMethodNode extends MethodNode, so i'll have MethodNode extend DecorableNode (and leave ClassMethodNode unchanged)

Change seems to have worked.  this is done.

note: i added the test for the above and got a surprising result.  i believe this may be a babel6 bug.  if you look at it in [astexplorer](http://astexplorer.net/#/qEr4KCcd0E), you'll see that only in this case, ExportNamedDeclaration picks up both comments, otherwise it has no comments.  in addition, the first comment is a leading comment for the decorator, and the second is a trailing comment, not a leading comment for the class.

i'd like to skip over this for now - it isn't a case that aurelia needs at present.

---

_[src/generators/ast.js, line 19 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJsJ6Cdptf2YdTfiT:-KAycmrlC-9fYQIXsp3p:-626923599) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L19)):_
had to do this because the export keyword was coming before the comments and generating incorrect output, so now `ExportNamedDeclarationNode` can do this:

``` javascript
  _toCode(ctx) {
    const comment = this._declaration.toCode({ ...ctx, level: 0, includeComment: true, includeCode: false });
    const decl = this._declaration.toCode({ ...ctx, level: 0, includeComment: false, includeCode: true });
    const suffix = this._declaration.preventSemi ? '' : ';';

    return `${comment}export ${decl}${suffix}`;
  }
```

(done)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36)_

**Comment by cmichaelgraham** [comment]
Review status: 13 of 24 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[src/generators/ast.js, line 9 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJ1uyiFe2yD1rujNB:-KAywWEgoFBq1yPfixXN:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L9)):_
Done.

---

_[src/generators/ast.js, line 19 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoJsJ6Cdptf2YdTfiT:-KAywReHYU4OdxhnPNwp:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L19)):_
Done.

---

_[src/generators/ast.js, line 264 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36#-KAoKyFNL0CoaBxvJxlA:-KAywOFsVEW04APo4I1M:-499146009) ([raw file](https://github.com/yolodev/babel-dts-generator/blob/1e494e570e547416ebd60d31691691ad5e86941f/src/generators/ast.js#L264)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36)_

**Comment by Alxandr** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/36)_

**Pull request merged**
