### PR TITLE
Feature rest parameters

### PR DESCRIPTION
**Pull request by cmichaelgraham**
[Review on Reviewable](https://reviewable.io/reviews/yolodev/babel-dts-generator/31)

### CODE REVIEW

**Comment by Alxandr** [comment]
I need to set up linting for this, but quick thing; make sure you have newlines at end of every file. Also, make sure tabulator is never used, replace with spaces. Most editors can be configured to do both of this for you automatically.



---

Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 318 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31#-K0mc3WfDOTaIvCOyKac)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/a7cf2c47ba2c18277d833a830f988d28ab63038d/src/index.js#L318)):</sup>
Wouldn't it make more sense to check `if(value.rest)`? Instead of calling `getFunctionTypeAnnotationParamter` on something that may or may not exist and check if the result is truthy?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31)

**Comment by cmichaelgraham** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 318 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31#-K0mc3WfDOTaIvCOyKac)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/a7cf2c47ba2c18277d833a830f988d28ab63038d/src/index.js#L318)):</sup>
Ok if I check before the call and the result being truthy in case something goes wrong in the call?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31)

**Comment by Alxandr** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 318 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31#-K0mc3WfDOTaIvCOyKac)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/a7cf2c47ba2c18277d833a830f988d28ab63038d/src/index.js#L318)):</sup>
No, well, the point is that if `value.rest` is nothing (ie, `null` I guess, or worstcase `undefined`), there is no point in calling `getFunctionTypeAnnotationParameter` on it. It's a wasted call which does nothing. And yes, the function is setup to handle it, but if you need to check for "hey, should I use rest parameters" anyways, why not just check before you go out and make the function call?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31)

**Comment by cmichaelgraham** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 318 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31#-K0mc3WfDOTaIvCOyKac)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/a7cf2c47ba2c18277d833a830f988d28ab63038d/src/index.js#L318)):</sup>
i didn't express the idea very well - i won't make the call if value.rest is undefined, but i still want to check that the result is truthy in the case where value.rest is defined, in case the data in value.rest doesn't produce something valid



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31)

**Comment by Alxandr** [comment]
Reviewed 21 of 41 files at r2.
Review status: 15 of 21 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 318 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31#-K0mc3WfDOTaIvCOyKac)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/a7cf2c47ba2c18277d833a830f988d28ab63038d/src/index.js#L318)):</sup>
Ah, yes. That's a fair point.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31)

**Comment by Alxandr** [comment]
Reviewed 6 of 6 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/31)

**Pull request merged**
