### PR TITLE
fix(exports): prevent export of private class and var

### PR DESCRIPTION
**Pull request by cmichaelgraham**
addresses #19

[Review on Reviewable](https://reviewable.io/reviews/yolodev/babel-dts-generator/20)

### CODE REVIEW

**Comment by Alxandr** [comment]
Could you fix this commit to only include 4548538?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/index.js, line 211 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/20#-Jtu-R2Cz5yDd7FfkSjp)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/4548538b866bbae78f65e66e4b6190e701042749/src/index.js#L211)):</sup>
Rather than returning a magic string `'ignore'`, return `null` (or empty string, though I prefer `null`).

---

<sup>**[src/index.js, line 218 [r1]](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/20#-Jtu-aEMnkwkF6cg5VHu)** ([raw file](https://github.com/yolodev/babel-dts-generator/blob/4548538b866bbae78f65e66e4b6190e701042749/src/index.js#L218)):</sup>
Same here, don't use `'ignore'` magic string.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/20)

**Comment by cmichaelgraham** [comment]
problem is, the empty string is returned when it isn't a class so it moves on to do another check for a different kind of export.  we need a way to alert the caller that it found a class, but the class is private and not to be exported, preventing the continued checking (which errors).  please advise on how you'd like to proceed. :+1:

**Comment by Alxandr** [comment]
The way I typically deal with needing magic values is with constant, non-string variables (which is actually supported in ES6, so yay).

What you can do is define (at either the top of the file, or at top of the closure) a `const IGNORED = {};`. Nice thing about this is that JS enforces reference equality on object (as opposed to string equality which it does on strings), so `IGNORED` will match only itself and nothing else (meaning if you need other magic variables, you can define them in the same style).

The thing you need to make sure of though, is that you check early for the ignored value (as it isn't a string, so doing string-operations on it will fail). But from what I can see from your code, you do that already.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/20)

**Comment by cmichaelgraham** [comment]
brilliant !!  i'll update the PR :+1:

**Comment by cmichaelgraham** [comment]
PR updated - i really like the solution :+1:

**Comment by Alxandr** [comment]
Still not too keen on the fact that the PR has a commit that isn't part of the intended commits, but I'll try to merge, and we'll see what happens. 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/yolodev/babel-dts-generator/20)

**Comment by cmichaelgraham** [comment]
Thanks !!! :+1:

**Pull request merged**
